#!/usr/bin/env python3
"""
local_sync.py — the fast path.

Runs every 60 seconds via launchd, ONLY while the Mac is awake. Handles
the "I just typed or checked something off, make it real everywhere
immediately" case. Does NOT sweep Gmail or Classroom — those are slow
and don't need sub-minute freshness, so they're left to cloud_sync.py
rather than burning this loop's speed on them.

This is the *primary* reminder path. cloud_sync.py also fires reminders
now, but deliberately runs ten minutes behind (see shared/reminders.py),
so anything this script can catch, it catches first. The cloud only
takes over for reminders this script was asleep for.

Setup: see README.md. The launchd plist is generated by generate_plist.py.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from shared import config, pipeline

SOURCE = "local_sync"


def main() -> int:
    config.load_dotenv()
    try:
        report = pipeline.run_sync_pass(SOURCE, send_reminders=True)
    except Exception as e:
        # Something global went wrong (bad token, Notion unreachable).
        # Print to stderr so it lands in sync-error.log, and exit
        # non-zero — but never raise, so launchd keeps the job scheduled
        # instead of backing it off.
        print(f"[{SOURCE}] FATAL: {e}", file=sys.stderr)
        return 1
    return pipeline.finish(report, SOURCE)


if __name__ == "__main__":
    sys.exit(main())
